const mongoose=require('mongoose')
const addressSchema=new mongoose.Schema(
    {
        userId:{
            type:String,
            required:true,
        },
        address:{
            type:String,
            required:true,
        },
        state:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true,
        },
        zipcode:{
            type:String,
            required:true,
        },
        country:{
            type:String,
            required:true
        },
        language:{
            type:String,
            required:true,
        },
        gender:{
            type:String,
            required:true
        }
    },{timestamps:true}
);
module.exports=mongoose.model("Address",addressSchema);